version: '3.8'

services:
  react-app:
    build:
      context: ./front-end/company-interface
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - flask-server

  flask-server:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
